Fashion-store-web/Controllers/CategoryController.cs
using Fashion_store_web.Dtos.Categories;
using Fashion_store_web.Service;
using Microsoft.AspNetCore.Mvc;

namespace Fashion_store_web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _categoryService.GetListAsync();
            return View(categories);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryDto item)
        {
            if (ModelState.IsValid)
            {
                await _categoryService.CreateAsync(item);
                TempData["success"] = "Category create success";
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete()
        {
            //Lay id
            if (!Request.RouteValues.TryGetValue("id", out var categoryId))
            {
                return RedirectToAction("Index");
            }
            var IsValidId = Guid.TryParse(Convert.ToString(categoryId), out Guid id);
            if (IsValidId)
            {
                var category = await _categoryService.GetById(id);
                if (category.Id != Guid.Empty && category.Id != null)
                {
                    return View(new CategoryDto()
                    {
                        Id = category.Id,
                        Name = category.Name,
                        Order = category.Order,
                        ParentId = category.ParentId,
                        Slug = category.Slug,
                        CreationTime = category.CreationTime,
                        LastModificationTime = category.LastModificationTime,
                    });
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (ModelState.IsValid)
            {
                await _categoryService.DeleteAsync(id);
                TempData["success"] = "Category delete successfully";
            }
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Update()
        {
            //Lay id
            if (!Request.RouteValues.TryGetValue("id", out var categoryId))
            {
                return RedirectToAction("Index");
            }
            var IsValidId = Guid.TryParse(Convert.ToString(categoryId), out Guid id);
            if (IsValidId)
            {
                var category = await _categoryService.GetById(id);
                if (category.Id != Guid.Empty && category.Id != null)
                {
                    return View(new UpdateCategoryDto()
                    {
                        Id = category.Id,
                        Name = category.Name,
                        ParentId = category.ParentId,
                        Slug = category.Slug
                    });
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateCategoryDto item)
        {
            if (ModelState.IsValid)
            {
                await _categoryService.UpdateAsync(item);
                TempData["success"] = "Category update success";
            }
            return RedirectToAction("Index");
        }
    }
}

Fashion-store-web/Controllers/ProductController.cs
using Fashion_store_web.Dtos.Products;
using Fashion_store_web.Dtos.ProductSizes;
using Fashion_store_web.Dtos.Sizes;
using Fashion_store_web.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Fashion_store_web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly ISizeService _sizeService;

        public ProductController(IProductService productService, ISizeService sizeService)
        {
            _productService = productService;
            _sizeService = sizeService;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetListAsync() ?? new List<ProductDto>();
            return View(products);
        }

        public async Task<IActionResult> Create()
        {
            var sizes = await _sizeService.GetListAsync();
            var sizeSelectList = sizes.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString(),
            }).ToList();
            return View(new CreateProductDto()
            {
                Sizes = new List<CreateProductSizeDto>(),
                SizeSelectList = sizeSelectList
            });
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductDto item)
        {
            if (ModelState.IsValid)
            {
                var create = await _productService.CreateAsync(item);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Fashion-store-web/Controllers/ProductImageController.cs
using Fashion_store_web.Dtos.ProductImage;
using Fashion_store_web.Service;
using Microsoft.AspNetCore.Mvc;

namespace Fashion_store_web.Controllers
{
    public class ProductImageController : Controller
    {
        private readonly IProductImageService _productImageService;

        public ProductImageController(IProductImageService productImageService)
        {
            _productImageService = productImageService;
        }

        public async Task<IActionResult> Index()
        {
            var productImages = await _productImageService.GetListAsync();
            return View(productImages);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductImageDto item)
        {
            if (ModelState.IsValid)
            {
                await _productImageService.CreateAsync(item);
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Update()
        {

            if (Request.RouteValues.TryGetValue("Id", out var productImageId))
            {
                if (Guid.TryParse(Convert.ToString(productImageId), out Guid id))
                {
                    var productImage = await _productImageService.GetById(id);
                    if (productImage.Id != Guid.Empty && productImage.Id != null)
                    {
                        return View(new UpdateProductImageDto
                        {
                            ProductId = productImage.ProductId,
                            Id = productImage.Id,
                            Name = productImage.Name,
                            ShortName = productImage.ShortName,
                            Description = productImage.Description,
                            Slug = productImage.Slug,
                        });
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateProductImageDto item)
        {
            if (ModelState.IsValid)
            {
                await _productImageService.UpdateAsync(item);
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete()
        {

            if (Request.RouteValues.TryGetValue("Id", out var productImageId))
            {
                if (Guid.TryParse(Convert.ToString(productImageId), out Guid id))
                {
                    var productImage = await _productImageService.GetById(id);
                    if (productImage.Id != Guid.Empty && productImage.Id != null)
                    {
                        return View(productImage);
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(ProductImageDto item)
        {
            if (ModelState.IsValid)
            {
                await _productImageService.DeleteAsync(item.Id.Value);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Fashion-store-web/Controllers/SizeController.cs
using Fashion_store_web.Dtos.Sizes;
using Fashion_store_web.Service;
using Microsoft.AspNetCore.Mvc;

namespace Fashion_store_web.Controllers
{
    public class SizeController : Controller
    {
        private readonly ISizeService _sizeService;

        public SizeController(ISizeService sizeService)
        {
            _sizeService = sizeService;
        }

        public async Task<IActionResult> Index()
        {
            var sizes = await _sizeService.GetListAsync();
            return View(sizes);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSizeDto item)
        {
            if (ModelState.IsValid)
            {
                var create = await _sizeService.CreateAsync(item);
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Update()
        {
            //Lay id
            if (!Request.RouteValues.TryGetValue("id", out var sizeId))
            {
                return RedirectToAction("Index");
            }
            var IsValidId = Guid.TryParse(Convert.ToString(sizeId), out Guid id);
            if (IsValidId)
            {
                var size = await _sizeService.GetById(id);
                if (size.Id != Guid.Empty && size.Id != null)
                {
                    return View(new UpdateSizeDto()
                    {
                        Id = size.Id,
                        Name = size.Name,
                        Code = size.Code
                    });
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateSizeDto item)
        {
            if (ModelState.IsValid)
            {
                var update = await _sizeService.UpdateAsync(item);
                return RedirectToAction("Index");
            }
            return View();
        }

        public async Task<IActionResult> Delete()
        {
            //Lay id
            if (!Request.RouteValues.TryGetValue("id", out var sizeId))
            {
                return RedirectToAction("Index");
            }
            var IsValidId = Guid.TryParse(Convert.ToString(sizeId), out Guid id);
            if (IsValidId)
            {
                var size = await _sizeService.GetById(id);
                if (size.Id != Guid.Empty && size.Id != null)
                {
                    return View(new SizeDto()
                    {
                        Id = size.Id,
                        Name = size.Name,
                        Code = size.Code,
                        CreationTime = size.CreationTime,
                        LastModificationTime = size.LastModificationTime,
                    });
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateSizeDto item)
        {
            if (ModelState.IsValid)
            {
                await _sizeService.DeleteAsync(item.Id);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Fashion-store-web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fashion_store_web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Fashion_store_web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link ref="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fashion_store_web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Size" asp-action="Index">Size</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductImage" asp-action="Index">ProductImage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Fashion_store_web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Fashion-store-web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}